version: '3'

services:

  mongo:
    image: mongo:3.2
    container_name: mongo
    ports: 
      - 27017:27017

  spark-mongo:
    image: josemyd/docker-spark-mongo
    container_name: spark-mongo
    depends_on:
    - mongo
